import { Download, X, ChevronLeft, ChevronRight, ChevronDown, Expand } from "lucide-react";
import { useState, useEffect } from "react";

// Full-size photos and their grid thumbnails (generated by `npm run photos`)
const photoModules = import.meta.glob<{ default: string }>('@/assets/photos/*.jpeg', { eager: true });
const thumbModules = import.meta.glob<{ default: string }>('@/assets/photos/thumbs/*.jpeg', { eager: true });

// Leadership photos live in the same folder but must not appear in the meetup gallery
const LEADERSHIP_PHOTO_FILES = [
  'WhatsApp Image 2026-01-25 at 9.59.07 PM.jpeg',
  'WhatsApp Image 2026-01-25 at 9.59.25 PM.jpeg',
  'WhatsApp Image 2026-01-25 at 9.59.57 PM.jpeg',
  'WhatsApp Image 2026-01-25 at 10.00.56 PM.jpeg',
  'WhatsApp Image 2026-01-25 at 10.01.18 PM.jpeg',
  'WhatsApp Image 2026-01-26 at 11.44.54 AM.jpeg',
  'WhatsApp Image 2026-01-30 at 11.50.07 AM.jpeg',
  'WhatsApp Image 2026-01-30 at 9.57.05 PM.jpeg',
];

const fileName = (path: string) => path.split('/').pop() ?? path;
const thumbsByName = Object.fromEntries(
  Object.entries(thumbModules).map(([path, module]) => [fileName(path), module.default]),
);

// Shown large as the first photo in the grid
const FEATURED_PHOTO_FILE = 'IMG_5636-Enhanced-NR.jpeg';

const photos = Object.entries(photoModules)
  .filter(([path]) => !LEADERSHIP_PHOTO_FILES.includes(fileName(path)))
  .sort(([a], [b]) => Number(fileName(b) === FEATURED_PHOTO_FILE) - Number(fileName(a) === FEATURED_PHOTO_FILE))
  .map(([path, module]) => ({ full: module.default, thumb: thumbsByName[fileName(path)] ?? module.default }));

const DRIVE_URL = "https://drive.google.com/drive/folders/15F0tofKt-YAMn_wJrlas2QwTPLuxPdcy";
const PREVIEW_COUNT = 9; // the featured photo plus eight, filling whole rows at every width

const Gallery = () => {
  const [selectedImageIndex, setSelectedImageIndex] = useState<number | null>(null);
  const [showAll, setShowAll] = useState(false);
  const visiblePhotos = showAll ? photos : photos.slice(0, PREVIEW_COUNT);

  const handleOpenImage = (index: number) => {
    setSelectedImageIndex(index);
    document.body.style.overflow = 'hidden'; // Prevent background scrolling
  };

  const handleCloseImage = () => {
    setSelectedImageIndex(null);
    document.body.style.overflow = 'unset'; // Restore scrolling
  };

  const step = (delta: number) =>
    setSelectedImageIndex((prev) => (prev === null ? null : (prev + delta + photos.length) % photos.length));

  // Handle keyboard navigation
  useEffect(() => {
    if (selectedImageIndex === null) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setSelectedImageIndex(null);
        document.body.style.overflow = 'unset';
      } else if (e.key === 'ArrowLeft') {
        e.preventDefault();
        step(-1);
      } else if (e.key === 'ArrowRight') {
        e.preventDefault();
        step(1);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [selectedImageIndex]);

  return (
    <section id="gallery" className="py-20 bg-[#f6f2ea] scroll-mt-24">
      <div className="container mx-auto px-4 lg:px-8">
        <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6 mb-10 lg:mb-12">
          <div className="max-w-2xl">
            <div className="flex items-center gap-3 mb-4">
              <span className="block h-0.5 w-8 lg:w-10 bg-community-warm" />
              <span className="text-xs sm:text-sm font-bold tracking-[0.22em] text-community-warm">COMMUNITY GALLERY</span>
            </div>
            <h2 className="font-display font-bold text-4xl sm:text-5xl lg:text-6xl leading-[1.02] tracking-tight text-[#17201b]">
              End of Year <span className="italic font-semibold text-[#0f2c20]">Meetup</span>
            </h2>
            <p className="mt-4 text-base sm:text-lg text-gray-600 leading-relaxed">
              Relive the beautiful moments from our End of Year Community Meetup — a celebration of unity, culture, and
              togetherness.
            </p>
          </div>
          <div className="flex flex-col sm:flex-row lg:flex-col xl:flex-row sm:items-center lg:items-end xl:items-center gap-3 sm:gap-5 shrink-0">
            <div className="text-sm text-gray-600">
              <span className="font-display font-bold text-2xl text-[#0f2c20] mr-1.5">{photos.length}</span>
              photos · 13 December 2025
            </div>
            <a
              href={DRIVE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center gap-2 rounded-full bg-[#0f2c20] px-6 py-3 text-sm font-semibold text-white hover:bg-[#1a4332] transition"
            >
              <Download className="w-4 h-4" />
              Download all photos
            </a>
          </div>
        </div>

        {/* Gallery Grid: the first photo is featured larger on wider screens */}
        <div className="grid grid-cols-2 lg:grid-cols-4 auto-rows-[150px] sm:auto-rows-[200px] lg:auto-rows-[220px] gap-3 sm:gap-4">
          {visiblePhotos.map((photo, index) => (
            <button
              key={photo.full}
              type="button"
              onClick={() => handleOpenImage(index)}
              aria-label={`View photo ${index + 1} of ${photos.length}`}
              className={`group relative overflow-hidden rounded-2xl bg-[#e5e1d8] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#e0b75a] ${
                index === 0 ? "col-span-2 row-span-2" : ""
              }`}
            >
              <img
                src={photo.thumb}
                alt={`End of Year Mulembe Community Meetup, photo ${index + 1}`}
                loading={index < 3 ? "eager" : "lazy"}
                decoding="async"
                className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
              />
              <span className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
              <span className="absolute bottom-3 right-3 flex h-9 w-9 items-center justify-center rounded-full bg-white/90 text-[#0f2c20] opacity-0 group-hover:opacity-100 transition-opacity">
                <Expand className="w-4 h-4" />
              </span>
            </button>
          ))}
        </div>

        {photos.length > PREVIEW_COUNT && (
          <div className="mt-8 flex justify-center">
            <button
              type="button"
              onClick={() => {
                if (showAll) document.getElementById("gallery")?.scrollIntoView({ behavior: "smooth" });
                setShowAll((v) => !v);
              }}
              aria-expanded={showAll}
              className="inline-flex items-center gap-2 rounded-full border-[1.5px] border-[#0f2c20]/30 bg-white px-7 py-3.5 text-sm sm:text-base font-semibold text-[#0f2c20] hover:border-[#0f2c20] transition"
            >
              {showAll ? "Show fewer photos" : `Show all ${photos.length} photos`}
              <ChevronDown className={`w-4 h-4 transition-transform ${showAll ? "rotate-180" : ""}`} />
            </button>
          </div>
        )}

        {/* Image Modal/Lightbox */}
        {selectedImageIndex !== null && (
          <div
            role="dialog"
            aria-modal="true"
            aria-label="Photo viewer"
            className="fixed inset-0 z-50 bg-black/95 backdrop-blur-sm flex items-center justify-center p-2 sm:p-4"
            onClick={handleCloseImage}
          >
            <button
              onClick={handleCloseImage}
              className="absolute top-2 right-2 sm:top-4 sm:right-4 z-10 bg-white/10 hover:bg-white/20 active:bg-white/30 backdrop-blur-sm text-white rounded-full p-2 sm:p-2.5 transition-colors touch-manipulation min-w-[44px] min-h-[44px] flex items-center justify-center"
              aria-label="Close"
            >
              <X className="w-5 h-5 sm:w-6 sm:h-6" />
            </button>

            {photos.length > 1 && (
              <>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    step(-1);
                  }}
                  className="absolute left-2 sm:left-4 top-1/2 -translate-y-1/2 z-10 bg-white/10 hover:bg-white/20 active:bg-white/30 backdrop-blur-sm text-white rounded-full p-2.5 sm:p-3 transition-colors touch-manipulation min-w-[44px] min-h-[44px] flex items-center justify-center"
                  aria-label="Previous image"
                >
                  <ChevronLeft className="w-5 h-5 sm:w-6 sm:h-6" />
                </button>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    step(1);
                  }}
                  className="absolute right-2 sm:right-4 top-1/2 -translate-y-1/2 z-10 bg-white/10 hover:bg-white/20 active:bg-white/30 backdrop-blur-sm text-white rounded-full p-2.5 sm:p-3 transition-colors touch-manipulation min-w-[44px] min-h-[44px] flex items-center justify-center"
                  aria-label="Next image"
                >
                  <ChevronRight className="w-5 h-5 sm:w-6 sm:h-6" />
                </button>
              </>
            )}

            <div
              className="relative max-w-7xl w-full h-full flex items-center justify-center"
              onClick={(e) => e.stopPropagation()}
            >
              <img
                src={photos[selectedImageIndex].full}
                alt={`End of Year Mulembe Community Meetup, photo ${selectedImageIndex + 1}`}
                className="max-w-full max-h-full w-auto h-auto object-contain rounded-lg shadow-2xl"
                style={{ maxHeight: 'calc(100vh - 120px)' }}
              />
            </div>

            <div className="absolute bottom-2 sm:bottom-4 left-1/2 -translate-x-1/2 bg-white/10 backdrop-blur-sm text-white px-3 sm:px-4 py-1.5 sm:py-2 rounded-full text-xs sm:text-sm font-medium">
              {selectedImageIndex + 1} / {photos.length}
            </div>
          </div>
        )}
      </div>
    </section>
  );
};

export default Gallery;
